on:
  workflow_dispatch:
    inputs:
name: Deploy Solution
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./src/landingzone/main.bicep
        parameters: 'baseName=smartfactorymanagement vm_admin_name=${{ secrets.VM_ADMIN_NAME }} vm_admin_password=${{ secrets.VM_ADMIN_PASSWORD }} publicKey=${{ secrets.PUBLIC_KEY}} allow_ssh_and_rdp_via_public_ip="true"'
        failOnStdErr: false